import type { NextPage } from 'next'
import Head from 'next/head'

import RichTextEditor from '../components/organisms/RichTextEditor'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center">
        <h1 className="my-10 text-2xl font-bold">Rich Text Editor</h1>
        <RichTextEditor />
      </div>
    </div>
  )
}

export default Home
